resources:
- name: repo
  type: git
  source:
    uri: https://github.com/tomtomtomtom44/test-node.git
    branch: master
    username: tomtomtomtom44
    password: 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

- name: node-image
  type: registry-image
  source:
    repository: node
    tag: fermium

- name: test_image
  type: registry-image
  source:
    repository: ((image-repo-name))/test-node
    username: ((registry-username))
    password: ((registry-password))
    tag: 1.0.0-SNAPSHOT

jobs:
- name: test
  plan:
  - get: node-image
  - get: repo
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["install"]
        dir: repo
  - task: test
    image: node-image
    config:
      inputs:
      - name: repo
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "test"]
        dir: repo
  # - load_var: version
  #   file: repo/package.json
  - task: build-and-push
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: repo
      outputs:
      - name: image
      params:
        CONTEXT: repo
      run:
        path: build
  - put: test_image
    params:
      image: image/image.tar

